# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
---
version: 2
archives:
  - id: dbc4go
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
before:
  hooks:
    - "go mod download"
builds:
  -
    env:
      - CGO_ENABLED=0
      - BUILDER=GoReleaser
    goos:
      - linux
      - darwin
      - windows
    main: ./cmd/

changelog:
  filters:
    include:
      - "^feature:"
      - "^fix:"
  sort: asc
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ .Tag }}-next"
project_name: dbc4go
