// Code generated by dbc4go, DO NOT EDIT.
package testdata

// @ensures something: @exists e @in r: @forall i @indexof g: e > g[i]
func foo(a []int) (r, g []int) {
	{ // Open contract scope
		// Function's contracts
		defer func() {
			cond := func() bool {
				for e := range r {
					cond := func() bool {
						cond := func() bool {
							for i := 0; i < len(g); i++ {
								cond := func() bool { return e > g[i] }
								if !cond() {
									return false
								}
							}
							return true
						}
						if !cond() {
							return false
						}
						return true
					}
					if cond() {
						return true
					}
				}
				return false
			}
			if !cond() {
				panic("function didn't ensure @exists e @in r: @forall i @indexof g: e > g[i]")
			}
		}()
	} // Close contract scope

	// implementation
}
