// Code generated by dbc4go, DO NOT EDIT.
package testdata

// @ensures all returned elements are positive: @forall i @indexof r: r[i] > 0
func square(a []int) (r []int) {
	{ // Open contract scope
		// Function's contracts
		defer func() {
			for i := 0; i < len(r); i++ {
				if !(r[i] > 0) {
					panic("function didn't ensure all returned elements are positive")
				}
			}
		}()
	} // Close contract scope

	// implementation
}

// @ensures @forall k @indexof r: r[k] > 0 ==> e % 2 == 0
func foo(a []int) (r []int) {
	{ // Open contract scope
		// Function's contracts
		defer func() {
			for k := 0; k < len(r); k++ {
				if !(!(r[k] > 0) || (e%2 == 0)) {
					panic("function didn't ensure @forall k @indexof r: r[k] > 0 ==> e % 2 == 0")
				}
			}
		}()
	} // Close contract scope

	// implementation
}
