// Code generated by dbc4go, DO NOT EDIT.
package testdata

// @ensures something: @forall e @in r: @exists i @indexof g: e > g[i]
func foo(a []int) (r, g []int) {
	{ // Open contract scope
		// Function's contracts
		defer func() {
			{
				cond := func() bool {
					for _, e := range r {
						cond := func() bool {
							for i, _ := range g {
								cond := func() bool { return e > g[i] }
								if cond() {
									return true
								}
							}
							return false
						}
						if !cond() {
							return false
						}
					}
					return true
				}
				if !cond() {
					panic("function didn't satisfy something")
				}
			}
		}()
	} // Close contract scope

	// implementation
}
