// Code generated by dbc4go, DO NOT EDIT.
package testdata

// @ensures all returned elements are positive: @forall e @in r: e > 0
func square(a []int) (r []int) {
	{ // Open contract scope
		// Function's contracts
		defer func() {
			for e := range r {
				if !(e > 0) {
					panic("function didn't ensure all returned elements are positive")
				}
			}
		}()
	} // Close contract scope

	// implementation
}

// @ensures @forall e @in r: e > 0 ==> e % 2 == 0
func foo(a []int) (r []int) {
	{ // Open contract scope
		// Function's contracts
		defer func() {
			for e := range r {
				if !(!(e > 0) || (e%2 == 0)) {
					panic("function didn't ensure @forall e @in r: e > 0 ==> e % 2 == 0")
				}
			}
		}()
	} // Close contract scope

	// implementation
}
