// Code generated by dbc4go, DO NOT EDIT.
package testdata

import "strings"

// @import strings
// @requires strings.Contains(a,":")
func importFoo(a string) {
	{ // Open contract scope
		// Function's contracts
		{
			cond := func() bool { return strings.Contains(a, ":") }
			if !cond() {
				panic("function caller didn't satisfy strings.Contains(a,\":\")")
			}
		}
	} // Close contract scope
}
