// Code generated by dbc4go, DO NOT EDIT.
package testdata

import "strings"

// @import strings
// @requires strings.Contains(a,":")
func importFoo(a string) {
	{ // Open contract scope
		// Function's contracts
		if !(strings.Contains(a, ":")) {
			panic("function caller didn't satisfied strings.Contains(a,\":\")")
		}
	} // Close contract scope
}
